#!/bin/bash

get_workspaces() {
    workspaces=($(i3-msg -t get_workspaces | jq -r -c '.[] | { "name": .name, "focused": .focused, "urgent": .urgent }'))

    json='['
    for workspace in "${workspaces[@]}"; do
        name=`echo "$workspace" | jq -r -c '.name'`
        focused=`echo "$workspace" | jq -r -c '.focused'`
        urgent=`echo "$workspace" | jq -r -c '.urgent'`
        if [[ "$name" == "main" ]]; then
            symbol="גּ"
            pretty="Main"
        elif [[ "$name" == "code" ]]; then
            symbol=""
            pretty="Code"
        elif [[ "$name" == "test" ]]; then
            symbol=""
            pretty="Test"
        else
            symbol=""
            pretty="$name"
        fi
        json="$json{\"symbol\":\"$symbol\",\"name\":\"$name\",\"pretty\":\"$pretty\",\"focused\":$focused,\"urgent\":$urgent},"
    done
    json="${json::-1}]"
    echo "$json"
}

get_workspaces

## Subscribe to workspace updates to refresh this script
i3-msg -t subscribe -m '[ "workspace" ]' | while read -r _ ; do
    get_workspaces
done
